INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2019', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2019', 'dd/MM/yyyy') - TO_DATE('01/01/2019', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/01/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/03/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('18/04/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('19/04/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('24/06/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/07/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('19/08/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('14/10/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('04/11/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('11/11/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2019', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;


INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2020', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2020', 'dd/MM/yyyy') - TO_DATE('01/01/2020', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('06/01/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('23/03/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('09/04/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('10/04/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('25/05/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('15/06/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('22/06/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('29/06/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/07/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('17/08/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('12/10/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('02/11/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('16/11/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/12/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2020', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;



INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2021', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2021', 'dd/MM/yyyy') - TO_DATE('01/01/2021', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('11/01/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('22/03/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/04/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('02/04/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('17/05/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('03/06/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('17/06/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('05/07/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/07/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('16/08/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('18/10/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/11/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('15/11/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/12/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2021', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;


INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2022', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2022', 'dd/MM/yyyy') - TO_DATE('01/01/2022', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('10/01/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('21/03/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('14/04/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('15/04/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('30/05/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/06/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('27/06/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('04/07/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/07/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('15/08/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('17/10/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/11/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('14/11/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/12/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2022', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;



INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2023', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2023', 'dd/MM/yyyy') - TO_DATE('01/01/2023', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('09/01/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/03/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('06/04/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/04/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('22/05/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('12/06/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('19/06/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('03/07/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/07/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('21/08/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('16/10/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('06/11/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('13/11/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/12/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2023', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;


INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2024', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2024', 'dd/MM/yyyy') - TO_DATE('01/01/2024', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/01/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/03/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('28/03/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('29/03/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('13/05/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('03/06/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('10/06/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('01/07/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/07/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('19/08/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('14/10/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('04/11/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('11/11/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('08/12/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2024', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;


INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2025', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2025', 'dd/MM/yyyy') - TO_DATE('01/01/2025', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('06/01/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('24/03/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('17/04/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('18/04/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('02/06/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('23/06/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('30/06/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/07/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('18/08/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('13/10/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('03/11/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('17/11/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/12/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2025', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;


INSERT INTO MAS_DIAS_NO_LABORALES (ID, FECHA, ESTADO)
SELECT MAS_DIAS_NO_LABORALES_ID_SEQ.NEXTVAL, FECHAS.FECHA,
    CASE WHEN CO.FECHA IS NOT NULL THEN 1 ELSE 1 END AS ESTADO
FROM (
    SELECT TRUNC(TO_DATE('01/01/2026', 'dd/MM/yyyy') + LEVEL - 1) AS FECHA
    FROM DUAL
    CONNECT BY LEVEL <= (TO_DATE('31/12/2026', 'dd/MM/yyyy') - TO_DATE('01/01/2026', 'dd/MM/yyyy') + 1)
) FECHAS
LEFT JOIN (
    SELECT TO_DATE('01/01/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('12/01/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('23/03/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('02/04/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('03/04/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('01/05/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('18/05/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/06/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('15/06/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('29/06/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('20/07/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('07/08/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('17/08/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('12/10/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('02/11/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
	UNION ALL SELECT TO_DATE('16/11/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('08/12/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
    UNION ALL SELECT TO_DATE('25/12/2026', 'dd/MM/yyyy') AS FECHA FROM DUAL
 ) CO ON FECHAS.FECHA = CO.FECHA
WHERE TO_CHAR(FECHAS.FECHA, 'D') IN ('7', '1') OR CO.FECHA IS NOT NULL;
