
delete from EVALUACION_FASE;

-- QUEJA EXTERNA COMISORIO EJE
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	1	,	10	,	14	,	1	,	3	,	1	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	2	,	11	,	10	,	1	,	3	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	3	,	6	,	11	,	1	,	3	,	1	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	4	,	9	,	6	,	1	,	3	,	1	,	4	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	5	,	12	,	9	,	1	,	3	,	1	,	5	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	6	,	8	,	12	,	1	,	3	,	1	,	6	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	7	,	15	,	8	,	1	,	3	,	1	,	7	,	null	,	null	,	null);
-- QUEJA EXTERNA DEVOLUCION ENTIDAD
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	6	,	10	,	14	,	2	,	3	,	1	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	7	,	11	,	10	,	2	,	3	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	8	,	9	,	11	,	2	,	3	,	1	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	9	,	8	,	9	,	2	,	3	,	1	,	4	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	10	,	15	,	8	,	2	,	3	,	1	,	5	,	null	,	null	,	null);
-- QUEJA EXTERNA INCORPORACION
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	11	,	10	,	14	,	3	,	3	,	1	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	12	,	11	,	10	,	3	,	3	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	13	,	6	,	11	,	3	,	3	,	1	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	14	,	9	,	6	,	3	,	3	,	1	,	4	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	15	,	12	,	9	,	3	,	3	,	1	,	5	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	16	,	8	,	12	,	3	,	3	,	1	,	6	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	17	,	15	,	8	,	3	,	3	,	1	,	7	,	null	,	null	,	null);
-- QUEJA EXTERNA REMISORIO EXTERNO
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	18	,	10	,	14	,	4	,	3	,	1	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	19	,	11	,	10	,	4	,	3	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	20	,	9	,	11	,	4	,	3	,	1	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	21	,	12	,	9	,	4	,	3	,	1	,	4	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	22	,	8	,	12	,	4	,	3	,	1	,	5	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	23	,	15	,	8	,	4	,	3	,	1	,	6	,	null	,	null	,	null);
-- QUEJA EXTERNA REMISORIO INTERNO
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	24	,	10	,	14	,	5	,	3	,	1	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	25	,	11	,	10	,	5	,	3	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	26	,	6	,	11	,	5	,	3	,	1	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	27	,	9	,	6	,	5	,	3	,	1	,	4	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	28	,	12	,	9	,	5	,	3	,	1	,	5	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	29	,	8	,	12	,	5	,	3	,	1	,	6	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	30	,	15	,	8	,	5	,	3	,	1	,	7	,	null	,	null	,	null);
-- TUTELA DIAS
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	31	,	17	,	10	,	6	,	4	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	32	,	9	,	17	,	6	,	4	,	1	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	33	,	18	,	9	,	6	,	4	,	1	,	4	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	34	,	15	,	18	,	6	,	4	,	1	,	5	,	null	,	null	,	null);
-- TUTELA HORAS
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	35	,	17	,	10	,	6	,	4	,	2	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	36	,	9	,	17	,	6	,	4	,	2	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	37	,	18	,	9	,	6	,	4	,	2	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	38	,	15	,	18	,	6	,	4	,	2	,	4	,	null	,	null	,	null);
-- DERECHO DE PETICION COPIAS
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	39	,	10	,	14	,	6	,	1	,	1	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	40	,	9	,	10	,	6	,	1	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	41	,	18	,	9	,	6	,	1	,	1	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	42	,	15	,	18	,	6	,	1	,	1	,	4	,	null	,	null	,	null);
-- DERECHO DE PETICION GENERAL
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	43	,	10	,	14	,	6	,	1	,	2	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	44	,	9	,	10	,	6	,	1	,	2	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	45	,	18	,	9	,	6	,	1	,	2	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	46	,	15	,	8	,	6	,	1	,	2	,	4	,	null	,	null	,	null);
-- DERECHO DE PETICION ALERTA
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	47	,	10	,	14	,	6	,	1	,	3	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	48	,	9	,	10	,	6	,	1	,	3	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	49	,	18	,	9	,	6	,	1	,	3	,	3	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	50	,	15	,	8	,	6	,	1	,	3	,	4	,	null	,	null	,	null);
-- QUEJA INTERNA COMISORIO EJE
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	51	,	11	,	14	,	1	,	3	,	2	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	52	,	9	,	11	,	1	,	3	,	2	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	53	,	15	,	9	,	1	,	3	,	2	,	3	,	null	,	null	,	null);
-- QUEJA INTERNA DEVOLUCION ENTIDAD
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	54	,	11	,	14	,	2	,	3	,	2	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	55	,	9	,	11	,	2	,	3	,	2	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	56	,	15	,	9	,	2	,	3	,	2	,	3	,	null	,	null	,	null);
-- QUEJA INTERNA INCORPORACION
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	57	,	11	,	14	,	3	,	3	,	2	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	58	,	9	,	11	,	3	,	3	,	2	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	59	,	15	,	9	,	3	,	3	,	2	,	3	,	null	,	null	,	null);
-- QUEJA INTERNA REMISORIO EXTERNO
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	60	,	11	,	14	,	4	,	3	,	2	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	61	,	9	,	11	,	4	,	3	,	2	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	62	,	15	,	9	,	4	,	3	,	2	,	3	,	null	,	null	,	null);
-- QUEJA INTERNA REMISORIO INTERNO
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	63	,	11	,	14	,	5	,	3	,	2	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	64	,	9	,	11	,	5	,	3	,	2	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	65	,	15	,	9	,	5	,	3	,	2	,	3	,	null	,	null	,	null);
-- PODER PREFERENTE EXTERNA
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	66	,	11	,	14	,	6	,	2	,	1	,	1	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	67	,	9	,	11	,	6	,	2	,	1	,	2	,	null	,	null	,	null);
Insert into EVALUACION_FASE (ID,ID_FASE_ACTUAL,ID_FASE_ANTECESORA,ID_RESULTADO_EVALUACION,ID_TIPO_EXPEDIENTE,ID_SUB_TIPO_EXPEDIENTE,ORDEN,CREATED_AT,UPDATED_AT,DELETED_AT) values (	68	,	15	,	9	,	6	,	2	,	1	,	3	,	null	,	null	,	null);
