-- SIRIUS DERECHO PETICION COPIAS CAPTURA Y REPARTO  REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	1	,	1	,	1	,	1	,	1	,	1	,	null	,	null	,	null);
-- SIRIUS DERECHO PETICION GENERAL  CAPTURA Y REPARTO  REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	2	,	1	,	1	,	2	,	1	,	1	,	null	,	null	,	null);
-- SIRIUS DERECHO PETICION ALERTA  CAPTURA Y REPARTO  REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	3	,	1	,	1	,	3	,	1	,	1	,	null	,	null	,	null);
-- SIRIUS DERECHO PETICION COPIAS  EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	4	,	1	,	1	,	1	,	2	,	4	,	null	,	null	,	null);
- SIRIUS DERECHO PETICION GENERAL EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	5	,	1	,	1	,	2	,	2	,	4	,	null	,	null	,	null);
-- SIRIUS DERECHO PETICION ALERTA  EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	6	,	1	,	1	,	3	,	2	,	4	,	null	,	null	,	null);
-- SIRIUS QUEJA EXTERNA CAPTURA Y REPARTO  REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	7	,	1	,	3	,	1	,	1	,	1	,	null	,	null	,	null);
-- SIRIUS QUEJA INTERNA CAPTURA Y REPARTO ASIGNADO A SI MISMO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	8	,	1	,	3	,	2	,	1	,	2	,	null	,	null	,	null);
-- SIRIUS QUEJA EXTERNA EVALUACION ASIGNACION DIRIGIDA
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	9	,	1	,	3	,	1	,	2	,	3	,	null	,	null	,	null);
-- SIRIUS QUEJA INTERNA EVALUACION ASIGNACION DIRIGIDA
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	10	,	1	,	3	,	2	,	2	,	3	,	null	,	null	,	null);
-- SIRIUS TUTELA DIAS CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	11	,	1	,	4	,	1	,	1	,	1	,	null	,	null	,	null);
-- SIRIUS TUTELA HORAS CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	12	,	1	,	4	,	2	,	1	,	1	,	null	,	null	,	null);
-- SIRIUS TUTELA HORAS CAPTURA Y REPARTO CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	13	,	1	,	4	,	2	,	2	,	4	,	null	,	null	,	null);
-- SINPROC DERECHO PETICION COPIAS CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	14	,	3	,	1	,	1	,	1	,	1	,	null	,	null	,	null);
-- SINPROC DERECHO PETICION GENERAL  CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	15	,	3	,	1	,	2	,	1	,	1	,	null	,	null	,	null);
-- SINPROC DERECHO PETICION ALERTA  CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	16	,	3	,	1	,	3	,	1	,	1	,	null	,	null	,	null);
-- SINPROC DERECHO PETICION COPIAS EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	17	,	3	,	1	,	1	,	2	,	4	,	null	,	null	,	null);
-- SINPROC DERECHO PETICION GENERAL EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	18	,	3	,	1	,	2	,	2	,	4	,	null	,	null	,	null);
-- SINPROC DERECHO PETICION ALERTA  EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	19	,	3	,	1	,	3	,	2	,	4	,	null	,	null	,	null);
 -- SINPROC QUEJA EXTERNA CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	20	,	3	,	3	,	1	,	1	,	1	,	null	,	null	,	null);
-- SINPROC QUEJA INTERNA CAPTURA Y REPARTO ASIGNADO A SI MISMO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	21	,	3	,	3	,	2	,	1	,	2	,	null	,	null	,	null);
-- SINPROC QUEJA EXTERNA EVALUACION ASIGNACION DIRIGIDA
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	22	,	3	,	3	,	1	,	2	,	3	,	null	,	null	,	null);
-- SINPROC QUEJA INTERNA EVALUACION ASIGNACION DIRIGIDA
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	23	,	3	,	3	,	2	,	2	,	3	,	null	,	null	,	null);
-- SINPROC TUTELA HORAS CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	24	,	3	,	4	,	1	,	1	,	1	,	null	,	null	,	null);
-- SINPROC TUTELA DIAS CAPTURA Y REPARTO REPARTO ALEATORIO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	25	,	3	,	4	,	2	,	1	,	1	,	null	,	null	,	null);
-- SINPROC TUTELA HORAS EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	26	,	3	,	4	,	1	,	2	,	4	,	null	,	null	,	null);
-- SINPROC TUTELA DIAS EVALUACION CIERRE DEFINITIVO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	27	,	3	,	4	,	2	,	2	,	4	,	null	,	null	,	null);
-- PODER PREFERNTE A SOLICITUD EXTERNA CAPTURA Y REPARTO ASIGNADO A SI MISMO
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	28	,	4	,	2	,	1	,	1	,	2	,	null	,	null	,	null);
-- PODER PREFERNTE A SOLICITUD EXTERNA CAPTURA Y REPARTO  ASIGNACION DIRIGIDA
Insert into CIERRE_ETAPA_CONFIGURACION (ID,ID_TIPO_PROCESO_DISCIPLINARIO,ID_TIPO_EXPEDIENTE,ID_SUBTIPO_EXPEDIENTE,ID_ETAPA,ID_TIPO_CIERRE_ETAPA,CREATED_AT,UPDATED_AT,DELETED_AT) values (	29	,	4	,	2	,	1	,	2	,	3	,	null	,	null	,	null);
commit;
